### ISSUE TITLE
Cần giúp đỡ

### ISSUE THREAD

**Issue by Tuki277** [ntkien2907/Vietnamese-Sentiment-Analysis#1]
Mình đang gặp vấn đề chạy project này, bạn có thể support mình với ạ

**Comment by ntkien2907** [comment]
Uhm, bạn đang gặp vấn đề gì?

**Comment by Tuki277** [comment]
![image](https://user-images.githubusercontent.com/58626944/209565694-4e2b2959-d57c-4d9e-ab58-6a3752207d84.png)
chỗ Upsampling vocab này lấy từ đâu ra bạn nhỉ ?, mình đg k hiểu chỗ này lắm

**Comment by ntkien2907** [comment]
![image](https://user-images.githubusercontent.com/50834300/209566006-37dc4c87-052c-448b-93d8-a791ed326d79.png)
Vocab nằm ở đây nha bạn. Đoạn này đúng ra phải nằm trên, ngay sau khi load dataset. Trong lúc refactor lại code mình quên sửa lại. Cám ơn bạn.

**Comment by Tuki277** [comment]
Ok, thanks bạn nhé :1st_place_medal:
